#!/usr/bin/env python3
"""Generate .cursorrules files from marketplace plugins."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
MARKETPLACE_PATH = PROJECT_ROOT / ".github" / "plugin" / "marketplace.json"
OUTPUT_DIR = PROJECT_ROOT / "dist" / "cursor"


def parse_frontmatter(content: str) -> tuple[str, str] | None:
    """Parse YAML frontmatter, return (name, body)."""
    m = re.match(r"^---\n(.*?)\n---\n(.*)", content, re.DOTALL)
    if not m:
        return None
    fm: dict[str, str] = {}
    for line in m.group(1).splitlines():
        idx = line.find(":")
        if idx == -1:
            continue
        fm[line[:idx].strip()] = line[idx + 1 :].strip()
    return (fm.get("name", "unknown"), m.group(2).strip())


def generate_cursorrules(name: str, body: str) -> str:
    return f"# Cursor Rules for {name}\n# Generated by AI Plugin Marketplace\n\n{body}\n"


def main() -> None:
    if not MARKETPLACE_PATH.exists():
        print("ERROR: marketplace.json not found. Run from project root.", file=sys.stderr)
        sys.exit(1)

    marketplace = json.loads(MARKETPLACE_PATH.read_text())
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    manifest: dict[str, str] = {}

    for entry in marketplace["plugins"]:
        plugin_dir = (PROJECT_ROOT / entry["entry"]).parent
        plugin_json = json.loads((plugin_dir / "plugin.json").read_text())

        for skill_rel in plugin_json.get("skills", []):
            skill_path = plugin_dir / skill_rel
            if not skill_path.exists():
                continue

            content = skill_path.read_text()
            parsed = parse_frontmatter(content)
            if not parsed:
                continue

            name, body = parsed
            cursor_content = generate_cursorrules(name, body)
            out_path = OUTPUT_DIR / f"{entry['name']}.cursorrules"
            out_path.write_text(cursor_content)
            manifest[entry["name"]] = f"{entry['name']}.cursorrules"
            print(f"  Generated: dist/cursor/{entry['name']}.cursorrules")

    (OUTPUT_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\nDone. {len(manifest)} .cursorrules file(s) generated.")
    print("Output: dist/cursor/")


if __name__ == "__main__":
    main()
